language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - sh -c "if [ `php-config --vernum` -ge 50500 ]; then printf "yes\n" | pecl install apcu-beta; fi"
  - phpenv config-add tests/travis/php.ini
  - phpenv config-add tests/travis/php-$TRAVIS_PHP_VERSION.ini

  - composer self-update
  - composer install --dev

script: scripts/behat

notifications:
  email: false
