language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - phpenv config-add tests/travis/php.ini
  - phpenv config-add tests/travis/php-$TRAVIS_PHP_VERSION.ini

  - composer self-update
  - composer install --dev

script: scripts/behat

matrix:
  allow_failures:
    - php: 5.4
    - php: 5.5

notifications:
  email: false
